name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        version: 5.15.0
        mirror: "http://mirrors.ocf.berkeley.edu/qt/"
    - name: get-cmake
      uses: lukka/get-cmake@v3.18.0
    - name: make
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make

    - uses: DoozyX/clang-format-lint-action@v0.9
      with:
        source: './src'
        extensions: 'h,cpp'
        clangFormatVersion: 10